### PR TITLE
ISSUE-5507: Prevents OMEdit from crashing when parsing textAnnotations

### LINKED ISSUE #5507: OMEdit crashes when text is written in icon view

### PR DESCRIPTION
**Pull request by JKRT**
New indexing operations were added in 53f0fcbc8aa1ab13cd05be2c26c83ec0e2794ec3  however the function guard was not changed. Causing crashes in some cases. 

This will prevent OMEdit from crashing and resolves #5507. Still I think there is somewere else in OMEdit were I need to populate that list with more information

After some testing it seems that these lists are different so having a guard might not be good. See this PL as a request for comments. An alternative would be to not index things in the list which we do not have and remove the guard. The real solution I guess would be to rewrite the option dialog for text annotation so that it matches the changes introduced by  53f0fcbc8aa1ab13cd05be2c26c83ec0e2794ec3

### CODE REVIEW

File: OMEdit/OMEdit/OMEditGUI/Annotations/TextAnnotation.cpp [hunk 1]
```diff
@@ -159,7 +159,7 @@ void TextAnnotation::parseShapeAnnotation(QString annotation)
   FilledShape::parseShapeAnnotation(annotation);
   // parse the shape to get the list of attributes of Text.
   QStringList list = StringHandler::getStrings(annotation);
-  if (list.size() < 12) {
+  if (list.size() < 15) {
```
Comment (JKRT) [inline OMEdit/OMEdit/OMEditGUI/Annotations/TextAnnotation.cpp]: Consider the code below it should be < 15. However, this is far from a proper solution I think

**Comment by casella** [comment]
@adrpo, @adeas31, this is too technical for me to judge if this fix is good enough or not, but as long as it fixes [#5507](https://trac.openmodelica.org/OpenModelica/ticket/5507) and it doesn't break anything else, I would suggest to merge it right away. Then, we could look for some better solutions without OMEdit crashing.

**Comment by JKRT** [comment]
> 
> 
> @adrpo, @adeas31, this is too technical for me to judge if this fix is good enough or not, but as long as it fixes [#5507](https://trac.openmodelica.org/OpenModelica/ticket/5507) and it doesn't break anything else, I would suggest to merge it right away. Then, we could look for some better solutions without OMEdit crashing.

It seems so the reason for the crash is that the parse code belows assumes that we have a list of atleast 15 in size (index 14). However, it is a ductape fix(!). Since the list seems to be able to vary in size having a guard does feel a little bit odd

**Comment by adrpo** [comment]
Should be fine now as I forced Text record to always show all the components by supplying default bindings to all the components that didn't have them (fontName, textStyle):
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/FrontEnd/Constants.mo#L339
Because this definition is used by both the current frontend (CF) and the new frontend (NF) we should no longer have any issues. 

Well, maybe if one has a Text that doesn't supply "extent" and "textString", we would have issues, maybe we should give some defaults for that as well (@adeas31, what is the default for "extent"?)

**Comment by adeas31** [comment]
A good default value for extent is `{{-10, -10}, {10, 10}}`. Set it for all the shapes then.
For textString an empty string as default is enough.

**Comment by JKRT** [comment]
@adeas31 the guard should stay and be 15 then?

**Comment by adeas31** [comment]
Yes!

**Comment by adrpo** [comment]
> A good default value for extent is `{{-10, -10}, {10, 10}}`. Set it for all the shapes then.
> For textString an empty string as default is enough.

Fixed in #233.
