### PR TITLE
Evaluate expressions in the annotation

### LINKED ISSUE #6111: Support for "visible" attribute missing in graphical annotation rendering of OMEdit
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6111

### LINKED ISSUE #9453: Expressions in annotations with instance api
### Description

Right now the instance api just dumps the expressions in the annotation.

### Steps to Reproduce

```
model IconVisible
parameter Boolean show=true;
annotation(
    Icon(graphics = {
    Rectangle(visible=not show, origin = {-40, 0}, extent = {{-20, 20}, {20, -20}}),
    Rectangle(visible=show,origin = {40, 0}, fillPattern = FillPattern.Solid, extent = {{-20, 20}, {20, -20}})}));
end IconVisible;
```

Calling `getModelInstance(IconVisible)` outputs,
<details><summary>Click to expand output</summary>

```
"{
  \"name\": \"IconVisible\",
  \"restriction\": \"model\",
  \"annotation\": {
    \"Icon\": {
      \"graphics\": [
        {
          \"$kind\": \"record\",
          \"name\": \"Rectangle\",
          \"elements\": [
            {
              \"$kind\": \"unary_op\",
              \"op\": \" not \",
              \"exp\": {
                \"$kind\": \"cref\",
                \"parts\": [
                  {
                    \"name\": \"show\"
                  }
                ]
              }
            },
            [
              -40,
              0
            ],
            0,
            [
              0,
              0,
              0
            ],
            [
              0,
              0,
              0
            ],
            {
              \"$kind\": \"enum\",
              \"name\": \"LinePattern.Solid\",
              \"index\": 2
            },
            {
              \"$kind\": \"enum\",
              \"name\": \"FillPattern.None\",
              \"index\": 1
            },
            0.25,
            {
              \"$kind\": \"enum\",
              \"name\": \"BorderPattern.None\",
              \"index\": 1
            },
            [
              [
                -20,
                20
              ],
              [
                20,
                -20
              ]
            ],
            0
          ]
        },
        {
          \"$kind\": \"record\",
          \"name\": \"Rectangle\",
          \"elements\": [
            {
              \"$kind\": \"cref\",
              \"parts\": [
                {
                  \"name\": \"show\"
                }
              ]
            },
            [
              40,
              0
            ],
            0,
            [
              0,
              0,
              0
            ],
            [
              0,
              0,
              0
            ],
            {
              \"$kind\": \"enum\",
              \"name\": \"LinePattern.Solid\",
              \"index\": 2
            },
            {
              \"$kind\": \"enum\",
              \"name\": \"FillPattern.Solid\",
              \"index\": 2
            },
            0.25,
            {
              \"$kind\": \"enum\",
              \"name\": \"BorderPattern.None\",
              \"index\": 1
            },
            [
              [
                -20,
                20
              ],
              [
                20,
                -20
              ]
            ],
            0
          ]
        }
      ]
    }
  },
  \"components\": [
    {
      \"name\": \"show\",
      \"type\": \"Boolean\",
      \"modifiers\": \"true\",
      \"value\": {
        \"binding\": true
      },
      \"prefixes\": {
        \"variability\": \"parameter\"
      }
    }
  ],
  \"source\": {
    \"filename\": \"C:/Users/adeas31/Desktop/ModelInstance/issue-6111.mo\",
    \"lineStart\": 1,
    \"columnStart\": 1,
    \"lineEnd\": 7,
    \"columnEnd\": 16
  }
}"
```
</details>

### Expected Behavior

Output both the original expression and the evaluated value.

### Additional Context

One idea is to improve the `Expression `class in OMEdit to evaluate such expressions. I am not sure about this but @perost knows more since he implemented it. Not sure if we can handle all cases with `Expression` class. For example, if the above model is used like this in another model,

```
model M
  IconVisible iconVisible(show=false)
    annotation (Placement(transformation(extent={{-74,-8},{-54,12}})));
  annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
        coordinateSystem(preserveAspectRatio=false)));
end M;
```

Then we need to apply the modifiers.

### PR DESCRIPTION
**Pull request by adeas31**
### Related Issues

Fixes #6111, fixes #9453

### Purpose

Handle the expression/variable used in the annotation for correct rendering of the graphics.

### Approach

Evaluate the expression and use the evaluated value for graphics.

### CODE REVIEW

File: OMEdit/OMEditLIB/FlatModelica/Expression.cpp [hunk 1]
```diff
@@ -1629,7 +1629,7 @@ namespace FlatModelica
 
   void Unary::print(std::ostream &os) const
   {
-    os << _op << _e;
+    os << _op << " " << _e;
```
Comment (perost) [inline OMEdit/OMEditLIB/FlatModelica/Expression.cpp:1632]: I guess this is to fix the output of `not`, but then it becomes wrong for `-` instead which shouldn't have a space between. I think adding a space here if the operator is `not` is probably the best solution.

File: OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp [hunk 2]
```diff
@@ -168,6 +168,7 @@ void BitmapAnnotation::parseShapeAnnotation()
   GraphicItem::parseShapeAnnotation(mpBitmap);
 
   mExtent = mpBitmap->getExtent();
+  mExtent.evaluate(mpBitmap->getParentModel());
```
Comment (perost) [inline OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp:171]: `evaluate` can throw an exception if the expression is invalid in some way, so you probably want to catch those somehow.

File: OMEdit/OMEditLIB/FlatModelica/Expression.cpp (hunk 1 above)
Comment (adeas31) [reply OMEdit/OMEditLIB/FlatModelica/Expression.cpp:1632]: Yes to fix the output of `not`. I believe we also need space for `or` and `and`. I am not sure which operators require space. Can you please fix this part?

File: OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp (hunk 2 above)
Comment (adeas31) [reply OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp:171]: Isn't it the `fromExp` that will throw the exception?

File: OMEdit/OMEditLIB/FlatModelica/Expression.cpp (hunk 1 above)
Comment (perost) [reply OMEdit/OMEditLIB/FlatModelica/Expression.cpp:1632]: Binary operators are always printed with spaces, the only issue is with the unary operators `not` and `-` where `not` requires a space while `-` should not have a space. So e.g.:
```
os << _op;

if (_op.type() == Operator::Not) {
  os << " ";
}

os << _e;
```

File: OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp (hunk 2 above)
Comment (perost) [reply OMEdit/OMEditLIB/Annotations/BitmapAnnotation.cpp:171]: With the latest commit it looks good. I also noticed that I pointed out the wrong location since I read this as calling `Expression::evaluate` at first, but now I see that it's only in `DynamicAnnotation` you do that.
