### PR TITLE
Fix time-related 3D animation issues

### LINKED ISSUE #10635: [OMEdit] 3D Animation uses invalid timestamps
### Description

Animation should not try to display a scene with timestamp outside the range [`StartTime`, `StopTime`].
Otherwise it produces invalid visualization objects since there is no more data provided beyond simulation stop time.
This implies I/O lag (e.g., when saving a model file), sometimes severely long, because of many messages like [this one](https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.6.5/src/osgUtil/CullVisitor.cpp#L959-L969):
```
CullVisitor::apply(Geode&) detected NaN,
    depth=-nan, center=(0 0 0),
    matrix={
        nan nan nan nan 
        nan nan nan nan 
        nan nan nan nan 
        nan nan nan nan 
}
```

### Steps to Reproduce

Test with `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` MSL example model.
It embeds a `Modelica.Blocks.Logical.TerminateSimulation` simulation termination condition block.

Pull the time slider to the end of its range, this will display a blank scene, then modify and save a model.

### LINKED ISSUE #10636: [OMEdit] 3D Animation does not always consider start time
### Description

Displayed time is currently in the range [`0`, `StopTime - StartTime`] when moving the slider manually.
Start time is not taken into account in range conversions between slider position and visualization time.

### Steps to Reproduce

Test with `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` MSL example model.
It embeds a `Modelica.Blocks.Logical.TerminateSimulation` simulation termination condition block.

Simulate with modified start time, it will start at the correct time, then move the time slider and it fails.

### LINKED ISSUE #10637: [OMEdit] 3D Animation shows mismatched timestamp of displayed scene
### Description

When using the timer (`Play`) with repetition (`Repeat`), at the stop time the displayed scene is already reinitialized.

### Steps to Reproduce

Test with `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` MSL example model.
It embeds a `Modelica.Blocks.Logical.TerminateSimulation` simulation termination condition block.

Enable animation repeat, play the animation, then pause it when the stop time is reached.
The scene is reinitialized to the start time while both the slider and text indicate the stop time.

### PR DESCRIPTION
**Pull request by anotheruserofgithub**
### Related Issues

1. Fixes #10635
2. Fixes #10636
3. Fixes #10637

### Purpose

Improve user's experience with 3D animation.

### Approach

1. Use `double` type instead of `float` in time computation.
2. Add start time in the computation of visualization time.
3. Reorder scene update and computation of next time.

Test model:
```modelica
model Test
  extends Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot;
equation
  annotation(experiment(StartTime = 1, StopTime = 2));
end Test;
```

### CODE REVIEW

**Comment by adeas31** [comment]
Sorry, I didn't get enough time for this. I will review it asap.

File: OMEdit/OMEditLIB/Animation/AbstractAnimationWindow.cpp [hunk 1]
```diff
@@ -218,17 +218,17 @@ void AbstractAnimationWindow::createActions()
   connect(mpPerspectiveDropDownBox, SIGNAL(activated(int)), this, SLOT(setPerspective(int)));
   // rotate camera left action
   mpRotateCameraLeftAction = new QAction(QIcon(":/Resources/icons/rotateCameraLeft.svg"), tr("Rotate Left"), this);
-  mpRotateCameraLeftAction->setStatusTip(tr("Rotates the camera left"));
+  mpRotateCameraLeftAction->setStatusTip(tr("Rotate the camera left"));
```
Comment (adeas31) [inline OMEdit/OMEditLIB/Animation/AbstractAnimationWindow.cpp:221]: Isn't it actually correct to use `Rotates`? It tells what this button does.

**Review by adeas31 — APPROVED** [review]
Looks good.

We need the same change for the slider in Variables Browser. Can you do that? Otherwise I will merge this and make a new PR.

**Review by adeas31 — APPROVED** [review]

**Comment by adeas31** [comment]
Thanks @anotheruserofgithub
