### PR TITLE
Free partially initialized linear systems for fmi2Reset

### LINKED ISSUE #6703: A bug in fmi2Reset?
Hi, 

I was refered to here from [fmpy](https://github.com/CATIA-Systems/FMPy/issues/162).

I was trying to do a parameter sweep with an FMUs generated from OpenModelica (2.0 both me and cs) but whenever I reset the FMU I get the following error:
```
Traceback (most recent call last): 
File ".../generate_fmu.py", line 24, in <module> res = model.simulate(experiment_settings) File "...\models.py", line 74, in simulate validate=False, input=self.input, output=self.output, start_values=self.start_values, **experiment_settings) 
File "....py", line 573, in simulate_fmu result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished)
File "...\fmpy\simulation.py", line 972, in simulateCS fmu.exitInitializationMode() 
File "...\fmpy\fmi2.py", line 286, in exitInitializationMode return self.fmi2ExitInitializationMode(self.component)
File "...\fmpy\fmi2.py", line 206, in w res = f(*args) OSError: exception: access violation writing 0x0000000000000000
```

This is e.g. one FMU that generates this error: [FMU](https://github.com/OpenModelica/OpenModelica/files/5056919/DynEq.ReferenceModel.1.zip)

And this problem can be recreated using this code:

```import fmpy

fmu_path = '' # SET THE PATH HERE
model_description = fmpy.read_model_description(fmu_path))
unzipdir = fmpy.extract(fmu_path)
fmu=fmpy.instantiate_fmu(unzipdir, model_description, 'ModelExchange')

for i in range(2):
    fmu.reset()
    res1 = fmpy.simulation.simulate_fmu(unzipdir, fmu_instance=fmu, model_description=model_description,
                                    validate=False, output=['source.P'])
```

The developer of fmpy says that's due to an error in fmi2reset function. Is there maybe a workaround for this?

### PR DESCRIPTION
**Pull request by AnHeuermann**
fixes #6703

  - Fixes segmentation fault while freeing linear systems that are not fully initialized
  - Check if parDynamicData is allocated, is NULL otherwise
  - Check if sparsity pattern was allocated before freeing parts of it

### CODE REVIEW

**Review by adrpo — APPROVED** [review]
OK by me!

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c [hunk 1]
```diff
@@ -393,6 +389,18 @@ int freeLinearSystems(DATA *data, threadData_t *threadData)
       freeAnalyticJacobian(jacobian);
       /* Note: The Jacobian of data->simulationInfo itself will be free later. */
 
+    if (linsys[i].parDynamicData == NULL)
```
Comment (mahge) [inline OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:392]: Is `parDynamicData` itself deleted somewhere? It should probably be.

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c [hunk 2]
```diff
@@ -393,6 +389,18 @@ int freeLinearSystems(DATA *data, threadData_t *threadData)
...
+    {
+      break;
+    }
+    else
+    {
+      for (j=0; j<omc_get_max_threads(); ++j)
+      {
+        free(linsys[i].parDynamicData[j].b);
```
Comment (mahge) [inline OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: Good idea to set `b` to NULL. I normally use a function called `delete_null()`  (or `free_null()` in this case) to delete and set to null. Instead of plain `free()`

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c (hunk 1 above)
Comment (AnHeuermann) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:392]: Yes, in https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c#L317

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c (hunk 2 above)
Comment (AnHeuermann) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: You mean after it is freed?

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c (hunk 1 above)
Comment (mahge) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:392]: Okay. Just making sure. It should be set to null there btw. Idk the workflow but if you check for null here after it is deleted it might break.

File: OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c (hunk 2 above)
Comment (mahge) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: Ya. I can see a cople of free calls followed by null assign here. So I am guessing there is some possibility of double free in mind.

Comment (AnHeuermann) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: When initializing struct `whateverTheNameWasForLinearSystems` I set all pointers in it to `NULL`. When it gets deleted I check if it was allocated at some point by checking if it `NULL`.
Setting it to NULL here as well can't hurt. I'm doing that for other variables as well.

Comment (mahge) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: Okay. I am just pointing them out in case you have overlooked them.

Comment (AnHeuermann) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c:400]: I think it shouldn't matter. `freeLinearSystems` should only be called once, at least at the moment.
I'm adding a few `NULL`s nonetheless they don't hurt and there are a few of them already.

Comment (mahge) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c]: >  at least at the moment.
There is the catch. It is better to be safe. Save time for your future self ☜(ﾟヮﾟ☜)

Comment (AnHeuermann) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c]: Yeah I can see myself cursing which idiot implemented this in a year only to do a git blame and find myself. :sweat_smile:

Comment (mahge) [reply OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c]: > I think it shouldn't matter. freeLinearSystems should only be called once
Btw it is not just about double free. The worst is when you use it after delete. It might work sometimes and segfault sometimes. Depending on weather the data has been overwritten since free.

NULL after free gives you a consistent crash in those cases.
