### PR TITLE
fix #13286: open files in binary mode

### LINKED ISSUE #13286: Copy command does not work on FMUs
### Description

Calling the `copy(from, to)` command from a .mos script usually works but not with FMUs.
The destination ends up being 1kB. It seems that copies only one of the internal files.
Tried also with admin rights, but nothing changes.

### Version and OS

 - OpenModelica Version: 1.24.2 (64bit)
 - OS: Win 11

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

File: OMCompiler/SimulationRuntime/c/util/omc_file.c [hunk 1]
```diff
@@ -134,7 +134,7 @@ int omc_fclose(FILE* stream)
  * @param size              Size in bytes of each element to read.
  * @param count             Number of elements to read, each with size `size` bytes.
  * @param stream            Pointer to FILE object with input stream.
- * @param allow_early_eof   Specifies wheather the call is okay or not with reaching
+ * @param allow_early_eof   Specifies weather the call is okay or not with reaching
```
Comment (perost) [inline OMCompiler/SimulationRuntime/c/util/omc_file.c:137]: whether

Comment (adrpo) [reply OMCompiler/SimulationRuntime/c/util/omc_file.c:137]: Yep
